server.port=8091
spring.data.mongodb.uri=mongodb+srv://gunasekharparisa2218_db_user:0LAqKwmWGbCVOaLf@cluster0.or9oxol.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true